{% set name = "davix" %}
{% set version = "0_8_0" %}

package:
  name: {{ name|lower }}
  version: {{ version.replace('_', '.') }}

source:
  url: https://github.com/cern-fts/davix/releases/download/R_{{ version }}/davix-{{ version.replace('_', '.') }}.tar.gz
  sha256: 2f108da0408a83fb5b9f0c68150d360ba733e4b3a0fe298d45b0d32d28ab7124

build:
  number: 0
  skip: true  # [win]
  run_exports:
    # https://abi-laboratory.pro/tracker/timeline/davix/
    - {{ pin_subpackage('davix', max_pin='x.x') }}
  ignore_run_exports:
    - libuuid

requirements:
  build:
    - gnuconfig  # [unix]
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - cmake
    - make
    - git
    - python <3
    - sed
    - pkg-config
    - gsoap
  host:
    - gsoap
    - openssl
    - libxml2
    - libuuid
    - zlib
  run:
    - openssl
    - libxml2
    - zlib

test:
  commands:
    # We expect davix-ls to exit with 1 if everything is okay
    - bash -c 'davix-ls --help && exit 3 || [ $? -eq 1 ]'
    # Check the pkg-config file is as expected
    - cat "${PREFIX}/lib/pkgconfig/davix.pc"
    - grep -q "${PREFIX}" "${PREFIX}/lib/pkgconfig/davix.pc"
    - bash -c 'grep -q "lib64" "${PREFIX}/lib/pkgconfig/davix.pc" && exit 3 || [ $? -eq 1 ]'

about:
  home: https://dmc.web.cern.ch/projects/davix/home
  license: LGPL-2.1-only
  license_file: LICENSE
  summary: High-performance data access client for HTTP-based protocols. (WebDAV / S3 / Microsoft Azure / HTTP)

  description: |
    The davix project aims to make file management over HTTP-based protocols
    simple. The focus is on high-performance remote I/O and data management of
    large collections of files. Currently, there is support for the WebDav,
    Amazon S3, Microsoft Azure, and HTTP protocols.
  doc_url: https://dmc-docs.web.cern.ch/dmc-docs/versions/docs/davix-epel/html/
  dev_url: https://github.com/cern-it-sdc-id/davix

extra:
  recipe-maintainers:
    - chrisburr
    - egpbos
    - henryiii
