appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
provider: {linux_aarch64: default, linux_ppc64le: default}
travis:
  secure: {BINSTAR_TOKEN: OQS5eTBfS/IDGmbyJTMIuTxM4qYo3VookZLy8d9vyU/ALuGKFAl/MlSLT1uc+8dPmhVk6jJvuAvm4IZnB8mhtbzt4HwpgbVwGnMZ2brGBwiy7T6fAreFNWF2j5ooYtt2OfRAvvzlcLsrGsYiZO5wx7nkj9W8y5VJR8ytH4ho+I4b5hnI0/Pt4jt75aG//B/xPy9N1QD4JypKe+4b1oWpXIBlnt8Q4KdQJgIPw52psMV0SH+gnDIaaxymbHttded9LfcnkOSoXEIR9sS5suomyL5gsd9EBtu8ICnm08fH96EY9P5Uz2nykT/tARJ+Vhv6PCiA6LLdHxdM1Rqu/Nk9IvMqLuGuA9DEVnLRMCVrhV3ll2tnAM+mv5i//9mrJ5mn6i5ZDqsSUOpZFNRxpigQk5OZpfraj+epgAUKbsE5MN8auUSFf1OKbU3NUVabQVf2QDGoy2XRaMYa2TQdPjqeJ8uuKDpPckBobfCcyssanMksPpaZI7Wwzw27L+hKfFKUziTzqtTo+B4GOVIEsItS4iJjvaymLprlvWoGV79qKUDCGpm1u4R2dSkUEe4lVRBuzigXSrdhXU9mIiNhe/ATTuB0IRaoVojpNaFlLW6Jk3R7Zr+3yB9ELXzpx2sTZNB3VcCCoxFfV1c30jJsXxgOuQSKBEh2ESUUlsk1RnGfeSs=}
